DROP TABLE MNEMONIC;
DROP TABLE EXTENDED_KEY;
DROP TABLE SECRET_KEY;
DROP TABLE ACCOUNT;
DROP TABLE ACCOUNT_JNL;
DROP TABLE ACCOUNT_SYS_PRM;

CREATE TABLE MNEMONIC
(
   ID                   CHAR(32) NOT NULL COMMENT 'id',
   ALIAS                VARCHAR(200) COMMENT '别名',
   PASSWORD             VARCHAR(500) NOT NULL COMMENT '密码',
   CREATE_TIME          TIMESTAMP NULL COMMENT '创建时间',
   MODIFY_TIME          TIMESTAMP NULL COMMENT '修改时间',
   PRIMARY KEY (ID)
);
ALTER TABLE MNEMONIC COMMENT '助记词表';

CREATE TABLE EXTENDED_KEY
(
   ID                   CHAR(32) NOT NULL COMMENT 'id',
   MNEMONIC_ID          CHAR(32) NOT NULL COMMENT '助记词id',
   EXTENDED_KEY_PATH    VARCHAR(200) COMMENT '扩展密钥路径',
   PASSWORD             VARCHAR(500) NOT NULL COMMENT '密码',
   CREATE_TIME          TIMESTAMP NULL COMMENT '创建时间',
   MODIFY_TIME          TIMESTAMP NULL COMMENT '修改时间',
   PRIMARY KEY (ID)
);
ALTER TABLE EXTENDED_KEY COMMENT '扩展密钥表';

CREATE TABLE SECRET_KEY
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  MNEMONIC_ID           CHAR(32) COMMENT '助记词id',
  EXTENDED_KEY_ID       CHAR(32) NOT NULL COMMENT '扩展密钥id',
  ADDRESS               VARCHAR(100) COMMENT '地址',
  PASSWORD              VARCHAR(500) NOT NULL COMMENT '密码',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE SECRET_KEY COMMENT '密钥表';

CREATE TABLE ACCOUNT
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  ADDRESS               VARCHAR(100) COMMENT '地址',
  COIN_TYPE             VARCHAR(20) COMMENT '币种',
  BALANCE               DECIMAL(35,20) NOT NULL COMMENT '余额',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE ACCOUNT COMMENT '账户表';

CREATE TABLE ACCOUNT_JNL
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  ACCOUNT_FROM          VARCHAR(100) COMMENT 'from地址',
  ACCOUNT_TO            VARCHAR(100) COMMENT 'to地址',
  COIN_TYPE             VARCHAR(20) COMMENT '币种',
  BALANCE               DECIMAL(35,20) NOT NULL COMMENT '金额',
  TYPE                  CHAR(2) COMMENT '类型(00:转入、01:转出)',
  TX_HASH               VARCHAR(200) COMMENT '交易hash',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE ACCOUNT_JNL COMMENT '账户流水表';

CREATE TABLE ACCOUNT_SYS_PRM
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  PRM_NAME              VARCHAR(100) NOT NULL COMMENT '参数名称',
  PRM_VALUE             VARCHAR(200) NOT NULL COMMENT '参数值',
  PRM_DESC              VARCHAR(200) COMMENT '参数描述',
  PRM_STATUS            CHAR(2) NOT NULL COMMENT '参数状态(01:有效、02:失效)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE ACCOUNT_SYS_PRM COMMENT '系统参数表';