DROP TABLE MNEMONIC;
DROP TABLE EXTENDED_KEY;
DROP TABLE SECRET_KEY;
DROP TABLE ACCOUNT;
DROP TABLE ACCOUNT_JNL;
DROP TABLE ACCOUNT_SYS_PRM;
DROP TABLE ADDRESS_REGISTER;
DROP TABLE WITHDRAWAL;
DROP TABLE ADDRESS_NOTICE;
DROP TABLE BLOCK_CHAIN_SYNC;
DROP TABLE TRANSACTION_ETH;
DROP TABLE TRANSACTION_BTC_UTXO;

CREATE TABLE MNEMONIC
(
   ID                   CHAR(32) NOT NULL COMMENT 'id',
   ALIAS                VARCHAR(200) COMMENT '别名',
   PASSWORD             VARCHAR(500) NOT NULL COMMENT '密码',
   CREATE_TIME          TIMESTAMP NULL COMMENT '创建时间',
   MODIFY_TIME          TIMESTAMP NULL COMMENT '修改时间',
   PRIMARY KEY (ID)
);
ALTER TABLE MNEMONIC COMMENT '助记词表';

CREATE TABLE EXTENDED_KEY
(
   ID                   CHAR(32) NOT NULL COMMENT 'id',
   MNEMONIC_ID          CHAR(32) NOT NULL COMMENT '助记词id',
   EXTENDED_KEY_PATH    VARCHAR(200) COMMENT '扩展密钥路径',
   PASSWORD             VARCHAR(500) NOT NULL COMMENT '密码',
   CREATE_TIME          TIMESTAMP NULL COMMENT '创建时间',
   MODIFY_TIME          TIMESTAMP NULL COMMENT '修改时间',
   PRIMARY KEY (ID)
);
ALTER TABLE EXTENDED_KEY COMMENT '扩展密钥表';

CREATE TABLE SECRET_KEY
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  MNEMONIC_ID           CHAR(32) COMMENT '助记词id',
  EXTENDED_KEY_ID       CHAR(32) NOT NULL COMMENT '扩展密钥id',
  ADDRESS               VARCHAR(100) COMMENT '地址',
  PASSWORD              VARCHAR(500) NOT NULL COMMENT '密码',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE SECRET_KEY COMMENT '密钥表';

CREATE TABLE ACCOUNT
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  ADDRESS               VARCHAR(100) COMMENT '地址',
  COIN_TYPE             VARCHAR(20) COMMENT '币种',
  TOTAL_IN              DECIMAL(65,0) COMMENT '入账总额',
  TOTAL_OUT             DECIMAL(65,0) COMMENT '出账总额',
  BALANCE               DECIMAL(65,0) NOT NULL COMMENT '余额',
  STATUS                VARCHAR(10) COMMENT '账户状态(CZSD:充值锁定、ZZSD:转出锁定、NORMAL:正常)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE ACCOUNT COMMENT '账户表';

CREATE TABLE ACCOUNT_JNL
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  ACCOUNT_FROM          VARCHAR(100) COMMENT 'from地址',
  ACCOUNT_TO            VARCHAR(100) COMMENT 'to地址',
  COIN_TYPE             VARCHAR(20) COMMENT '币种',
  BALANCE               DECIMAL(65,0) NOT NULL COMMENT '金额',
  TYPE                  CHAR(2) COMMENT '类型(00:转入、01:转出)',
  TX_HASH               VARCHAR(32) COMMENT '交易id',
  TRANS_TIME            TIMESTAMP NULL COMMENT '交易时间',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE ACCOUNT_JNL COMMENT '账户流水表';

CREATE TABLE ACCOUNT_SYS_PRM
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  PRM_NAME              VARCHAR(100) NOT NULL COMMENT '参数名称',
  PRM_VALUE             VARCHAR(200) NOT NULL COMMENT '参数值',
  PRM_DESC              VARCHAR(200) COMMENT '参数描述',
  PRM_STATUS            CHAR(2) NOT NULL COMMENT '参数状态(01:有效、02:失效)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE ACCOUNT_SYS_PRM COMMENT '系统参数表';

CREATE TABLE ADDRESS_REGISTER
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  ADDRESS               VARCHAR(100) COMMENT '地址',
  CONTRACT_ADDRESS      VARCHAR(100) COMMENT '合约地址',
  COIN_TYPE             VARCHAR(20) COMMENT '币种',
  SUB_COIN_TYPE         VARCHAR(20) COMMENT '子币种',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE ADDRESS_REGISTER COMMENT '地址注册表';

CREATE TABLE WITHDRAWAL
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  WITHDRAWAL_ID         CHAR(32) NOT NULL COMMENT '取现唯一编号',
  COIN_TYPE             VARCHAR(20) NOT NULL COMMENT '币种',
  SUB_COIN_TYPE         VARCHAR(20) COMMENT '子币种',
  ADDRESS               VARCHAR(100) NOT NULL COMMENT '地址',
  AMOUNT                DECIMAL(65,0) COMMENT '金额',
  TX_HASH               VARCHAR(100) COMMENT '交易hash',
  STATUS                VARCHAR(20) NOT NULL COMMENT '处理状态(CZWCL:充值未处理、CZCLZ:充值处理中、SUCCESS:充值成功、FAIL:充值失败)',
  TASK_STATUS           VARCHAR(20) NOT NULL COMMENT '处理状态(WCL:未处理、CLZ:处理中、SUCCESS:处理成功、FAIL:处理失败)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE WITHDRAWAL COMMENT '提现表';

CREATE TABLE ADDRESS_NOTICE
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  ADDRESS_REGISTER_ID   CHAR(32) NOT NULL COMMENT '地址注册id',
  ADDRESS               VARCHAR(100) NOT NULL COMMENT '地址',
  COIN_TYPE             VARCHAR(20) NOT NULL COMMENT '币种',
  NOTICE_ADDRESS        VARCHAR(2000) NOT NULL COMMENT '通知地址',
  NOTICE_TYPE           VARCHAR(20) NOT NULL COMMENT '通知类型(deposit:充值、withdrawal:取现)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE ADDRESS_REGISTER COMMENT '地址通知表';

CREATE TABLE BLOCK_CHAIN_SYNC
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  BLOCK_CHAIN_TYPE      VARCHAR(50) NOT NULL COMMENT '区块类型(BTC:比特币、ETH:以太坊)',
  CURRENT_SYNC_BLOCK_NUMBER        BIGINT COMMENT '当前同步区块数',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE BLOCK_CHAIN_SYNC COMMENT '区块同步表';

CREATE TABLE TRANSACTION_ETH
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  TX_HASH               VARCHAR(100) NOT NULL COMMENT '交易hash',
  BLOCK_NUMBER          BIGINT COMMENT '区块号',
  TX_FROM               VARCHAR(100) COMMENT 'FORM地址',
  TX_TO                 VARCHAR(100) COMMENT 'TO地址',
  CONTRACT_ADDRESS      VARCHAR(100) COMMENT '合约地址',
  COIN_TYPE             VARCHAR(20) COMMENT '币种',
  TX_INPUT              VARCHAR(2000) COMMENT 'input',
  TX_VALUE              DECIMAL(65,0) COMMENT '交易值',
  TX_INDEX              BIGINT COMMENT 'tx index',
  GAS_LIMIT             BIGINT COMMENT 'gas limit',
  GAS_USED              BIGINT COMMENT 'gas used',
  GAS_PRICE             BIGINT COMMENT 'gas price',
  ACTUAL_FEE            BIGINT COMMENT 'actual fee',
  NONCE                 BIGINT COMMENT 'nonce',
  TX_RECEIPT_STATUS     CHAR(1) NOT NULL COMMENT '交易状态(S:成功、F:失败、P:处理中)',
  TX_TIME               TIMESTAMP NULL COMMENT '交易时间',
  CONFIRM_BLOCK_NUMBER  INT COMMENT '确认区块数',
  TX_TYPE               CHAR(1) NOT NULL COMMENT '交易类型(0:转入、1:转出)',
  TX_STATUS             VARCHAR(20) NOT NULL COMMENT '交易状态(WCL:未处理、CZCLZYTZ:充值处理中已通知、QKQRSCLZ:区块确认数处理中、YEWQR:余额未确认、YEQRYC:余额确认异常、YX:有效、WX:无效)',
  TASK_STATUS           VARCHAR(20) NOT NULL COMMENT '处理状态(WCL:未处理、CLZ:处理中、SUCCESS:处理成功、FAIL:处理失败)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE TRANSACTION_ETH COMMENT 'ETH交易表';

CREATE TABLE TRANSACTION_BTC_UTXO
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  TX_HASH               VARCHAR(100) NOT NULL COMMENT '交易hash',
  VIN_TX_HASH           VARCHAR(100) COMMENT 'vin交易hash',
  VIN_TX_INDEX          BIGINT COMMENT 'vin tx index',
  BLOCK_NUMBER          BIGINT COMMENT '区块号',
  TX_FROM               VARCHAR(100) COMMENT 'FORM地址',
  TX_TO                 VARCHAR(100) COMMENT 'TO地址',
  TX_VALUE              DECIMAL(65,0) COMMENT '交易值',
  TX_INDEX              BIGINT COMMENT 'tx index',
  ACTUAL_FEE            BIGINT COMMENT 'actual fee',
  TX_TIME               TIMESTAMP NULL COMMENT '交易时间',
  CONFIRM_BLOCK_NUMBER  INT COMMENT '确认区块数',
  TX_TYPE               CHAR(1) NOT NULL COMMENT '交易类型(0:转入、1:转出)',
  TX_STATUS             VARCHAR(20) NOT NULL COMMENT '交易状态(WCL:未处理、CZCLZYTZ:充值处理中已通知、QKQRSCLZ:区块确认数处理中、YEWQR:余额未确认、YEQRYC:余额确认异常、YX:有效、WX:无效)',
  TASK_STATUS           VARCHAR(20) NOT NULL COMMENT '处理状态(WCL:未处理、CLZ:处理中、SUCCESS:处理成功、FAIL:处理失败)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE TRANSACTION_BTC_UTXO COMMENT 'BTC交易UTXO表';