DROP TABLE MNEMONIC;
DROP TABLE EXTENDED_KEY;
DROP TABLE SECRET_KEY;
DROP TABLE ADDRESS_REGISTER;
DROP TABLE ADDRESS_NOTICE;
DROP TABLE BLOCK_CHAIN_SYNC;
DROP TABLE TRANSACTION_ETH;

CREATE TABLE MNEMONIC
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  FILE_PATH             VARCHAR(5000) COMMENT '文件路径',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE MNEMONIC COMMENT '助记词表';

CREATE TABLE EXTENDED_KEY
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  MNEMONIC_ID           CHAR(32) NOT NULL COMMENT '助记词id',
  EXTENDED_KEY_PATH     VARCHAR(200) COMMENT '扩展密钥路径',
  FILE_PATH             VARCHAR(5000) COMMENT '文件路径',
  CURRENT_INDEX_NUMBER  INT COMMENT '当索引号',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE EXTENDED_KEY COMMENT '扩展密钥表';

CREATE TABLE SECRET_KEY
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  MNEMONIC_ID           CHAR(32) COMMENT '助记词id',
  EXTENDED_KEY_ID       CHAR(32) NOT NULL COMMENT '扩展密钥id',
  ADDRESS               VARCHAR(100) COMMENT '地址',
  KEY_PATH              VARCHAR(200) COMMENT 'key路径',
  FILE_PATH             VARCHAR(5000) COMMENT '文件路径',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE SECRET_KEY COMMENT '密钥表';

CREATE TABLE ADDRESS_REGISTER
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  ADDRESS               VARCHAR(100) COMMENT '地址',
  CONTRACT_ADDRESS      VARCHAR(100) COMMENT '合约地址',
  COIN_TYPE             VARCHAR(20) COMMENT '币种',
  SUB_COIN_TYPE         VARCHAR(20) COMMENT '子币种',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE ADDRESS_REGISTER COMMENT '地址注册表';

CREATE TABLE ADDRESS_NOTICE
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  ADDRESS_REGISTER_ID   CHAR(32) NOT NULL COMMENT '地址注册id',
  NOTICE_ADDRESS        VARCHAR(2000) COMMENT '通知地址',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE ADDRESS_REGISTER COMMENT '地址通知表';

CREATE TABLE BLOCK_CHAIN_SYNC
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  BLOCK_CHAIN_TYPE      VARCHAR(50) NOT NULL COMMENT '区块类型(BTC:比特币、ETH:以太坊)',
  CURRENT_SYNC_BLOCK_NUMBER        BIGINT COMMENT '当前同步区块数',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE BLOCK_CHAIN_SYNC COMMENT '区块同步表';

CREATE TABLE TRANSACTION_ETH
(
  TX_HASH               VARCHAR(100) NOT NULL COMMENT '交易hash',
  BLOCK_NUMBER          BIGINT COMMENT '区块号',
  TX_FROM               VARCHAR(100) COMMENT 'FORM地址',
  TX_TO                 VARCHAR(100) COMMENT 'TO地址',
  CONTRACT_ADDRESS      VARCHAR(100) COMMENT '合约地址',
  TX_INPUT              VARCHAR(1000) COMMENT 'input',
  TX_VALUE              VARCHAR(100) COMMENT '交易值',
  TX_INDEX              BIGINT COMMENT 'tx index',
  GAS_LIMIT             BIGINT COMMENT 'gas limit',
  GAS_USED              BIGINT COMMENT 'gas used',
  GAS_PRICE             BIGINT COMMENT 'gas price',
  ACTUAL_FEE            BIGINT COMMENT 'actual fee',
  NONCE                 BIGINT COMMENT 'nonce',
  TX_RECEIPT_STATUS     CHAR(1) NOT NULL COMMENT '交易状态(S:成功、F:失败、P:处理中)',
  TX_TIME               TIMESTAMP NULL COMMENT '交易时间',
  CONFIRM_BLOCK_NUMBER  INT COMMENT '确认区块数',
  TX_STATUS             VARCHAR(10) NOT NULL COMMENT '交易是否有效(WCL:未处理、CLZ:处理中、YX:有效、WX:无效)',
  TX_TYPE               CHAR(1) NOT NULL COMMENT '交易类型(0:转入、1:转出)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (TX_HASH)
);
ALTER TABLE TRANSACTION_ETH COMMENT 'ETH交易表';